# Generated by Django 4.1 on 2023-11-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0005_questionoption_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionoption",
            name="question_type",
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[("S", "Single"), ("M", "Multiple")], default="S", max_length=1
            ),
        ),
    ]
