# Generated by Django 4.1 on 2023-11-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_questionoption_priority_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoption',
            name='priority',
        ),
    ]
