# Generated by Django 4.1 on 2023-11-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_questionoption_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='blank_vote',
            field=models.BooleanField(default=False, verbose_name='Blank Vote'),
        ),
    ]
