# Generated by Django 4.1 on 2023-12-17 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0007_alter_question_question_type"),
        ("voting", "0011_alter_question_question_type"),
    ]

    operations = []
