# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from tests import LoginViewTestCase

class TestTestselenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testselenium(self):
    self.driver.get("http://localhost:8000/signin/")
    self.driver.set_window_size(990, 656)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys(LoginViewTestCase.user.username)
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys(LoginViewTestCase.user.password)
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  