# Generated by Django 4.1 on 2023-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_vote_id_voteoption_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='p',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
